setup: 
  - name: synchronize system time
    cmd: sudo systemctl restart systemd-timesyncd.service
  - name: update apt
    cmd: sudo apt update
  - name: remove flash-kernel
    cmd: sudo apt remove -y flash-kernel && sudo apt -y autoremove
  - name: install java 11
    cmd:  sudo apt install -y openjdk-11-jdk-headless -qq
  - name: install debconf-utbakerils
    cmd: sudo apt install -y debconf-utils -qq
  - name: set DEBIAN_FRONTEND as "noninteractive"
    cmd: export DEBIAN_FRONTEND="noninteractive"
  - name: set mysql root password
    cmd: echo "mysql-server mysql-server/root_password password {MYSQL_PSSW}" | sudo debconf-set-selections
  - name: set mysql root password again
    cmd: echo "mysql-server mysql-server/root_password_again password {MYSQL_PSSW}" | sudo debconf-set-selections
  - name: install mysql 8
    cmd: sudo apt install -y mysql-server -qq
  - name: install maven
    cmd: sudo apt install -y maven -qq
  - name: install git
    cmd: sudo apt install -y git -qq
  - name: get dependencies for nodejs
    cmd: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo bash -
  - name: install nodejs and npm
    cmd: sudo apt install -y nodejs -qq
  - name: install uuid for pm2
    cmd: sudo npm install uuid@latest -g
  - name: instal pm2
    cmd: sudo npm install pm2 -g
  - name: install yargs for npm
    cmd: npm install yargs
  - name: install browser for puppeteer
    cmd: sudo apt install -y chromium-browser chromium-bsu -qq
  - name: install canvas dependencies
    cmd: sudo apt install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  - name: stop apt-daily timer to look for updates
    cmd: sudo systemctl stop apt-daily.timer

jobs:
  - name: itrust-build
    steps:
      - name: clone latest version of iTrust2
        cmd: git clone https://{GIT_USER}:{TOKEN}@github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git
      - name: copy  application.yml.template to application.yml
        cmd: cp iTrust2-v10/iTrust2/src/main/resources/application.yml.template iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: update password in application.yml
        cmd: sed -i 's/password:/password:\ {MYSQL_PSSW}/' iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: Run iTrust2
        cmd: cd iTrust2-v10/iTrust2 && mvn --batch-mode --update-snapshots clean test
      - name: package iTrust2
        cmd: cd iTrust2-v10/iTrust2 && mvn clean package -Dmaven.test.skip=true
      - name: move iTrust2 jar file
        cmd: cp iTrust2-v10/iTrust2/target/iTrust2-10.jar /bakerx/
    cleanup:
      - name: remove iTrust2-v10 repo
        cmd: rm -rf iTrust2-v10
  - name: mutation-coverage
    steps:
      - name: remove screenshot folder
        cmd: rm -rf {VOLUME}/screenshots
      - name: make directory for screenshotsbaker
        cmd: mkdir {VOLUME}/screenshots
      - name: move Testharness to ~/
        cmd: cp -r {VOLUME}/ASTRewrite ASTRewrite/
      - name: install node dependencies for Testharness
        cmd: cd ~/ASTRewrite && npm install && cd
    mutation:
      url: https://github.com/chrisparnin/checkbox.io-micro-preview
      jsfile: checkbox.io-micro-preview/marqdown.js
      iterations: 10
      snapshots:
        - http://localhost:3000/survey/long.md
        - http://localhost:3000/survey/upload.md
        - http://localhost:3000/survey/survey.md
        - http://localhost:3000/survey/variations.md
    cleanup:
      - name: remove all web from pm2
        cmd: pm2 kill
      - name: remove ASTRewrite repo
        cmd: rm -rf ASTRewrite
      - name: remove microservice repo
        cmd: rm -rf checkbox.io-micro-preview
  - name: deploy-iTrusts
    steps:
      - name: move the project to the remote server
        scp:
          params:
            src: ./iTrust2-10.jar
            dest: ~/iTrust2-10.jar
      - name: shutdown the server 
        cmd: sudo killall -q 'java' || true
      - name: start the iTrust2 server 1
        cmd: nohup java -jar ~/iTrust2-10.jar --server.port=8080  &> /bakerx/server1.log &
      - name: start the iTrust2 server 2
        cmd: nohup java -jar ~/iTrust2-10.jar --server.port=8081  &> /bakerx/server2.log  &
    cleanup:
