setup: 
  - name: synchronize system time
    cmd: sudo systemctl restart systemd-timesyncd.service
  - name: update apt
    cmd: sudo apt update
  - name: remove flash-kernel
    cmd: sudo apt remove -y flash-kernel && sudo apt -y autoremove
  - name: install java 11
    cmd:  sudo apt install -y openjdk-11-jdk-headless -qq
  - name: download maven
    cmd: sudo wget https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz -P /tmp
  - name: clean maven sumbolic link 
    cmd: sudo rm /opt/maven || true
  - name: unzip maven
    cmd: sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt
  - name: create symbolic for maven
    cmd: sudo ln -s /opt/apache-maven-3.8.5 /opt/maven
  - name: stop apt-daily timer to look for updates
    cmd: sudo systemctl stop apt-daily.timer

jobs:
  - name: jenkins-build
    steps:
      - name: clone latest version of jenkins
        cmd: git clone https://github.com/jenkinsci/jenkins.git
      - name: package jenkins
        cmd: "cd jenkins && /opt/maven/bin/mvn -am -pl war,bom -DskipTests -Dspotbugs.skip -Dspotless.check.skip clean install"
      - name: move jenkins war file
        cmd: cp jenkins/war/target/jenkins.war /bakerx/jenkins.war
    cleanup:
      - name: remove jenkins repo
        cmd: rm -rf ~/jenkins
  - name: jenkins-unit-test
    steps:
      - name: clone latest version of jenkins
        cmd: git clone https://github.com/jenkinsci/jenkins.git
      - name: package jenkins
        cmd: "cd jenkins && /opt/maven/bin/mvn clean install -P light-test"
    cleanup:
      - name: remove jenkins repo
        cmd: rm -rf ~/jenkins
  - name: jenkins-smoke-test
    steps:
      - name: clone latest version of jenkins
        cmd: git clone https://github.com/jenkinsci/jenkins.git
      - name: package jenkins
        cmd: "cd jenkins && /opt/maven/bin/mvn clean install -P smoke-test"
    cleanup:
      - name: remove jenkins repo
        cmd: rm -rf ~/jenkins
  - name: jenkins-all-test
    steps:
      - name: clone latest version of jenkins
        cmd: git clone https://github.com/jenkinsci/jenkins.git
      - name: package jenkins
        cmd: "cd jenkins && /opt/maven/bin/mvn clean install -P all-test"
    cleanup:
      - name: remove jenkins repo
        cmd: rm -rf ~/jenkins
  - name: deploy-jenkins
    target: jenkins.war
    steps:
      - name: move the project to the remote server
        scp:
          params:
            server: jenkins
            src: ./jenkins.war
            dest: ~/jenkins.war
      - name: shutdown the server 
        cmd: sudo killall -q 'java' || true
      - name: start the jenkins on the server jenkins
        cmd: nohup java -jar ~/jenkins.war --httpPort=8081 &> /bakerx/jenkins.log &
      - name: copy jenkins password
        cmd : cp /home/vagrant/.jenkins/secrets/initialAdminPassword /bakerx/initialAdminPassword
    cleanup:
